name: CI/CD Lambda TS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 01-node-ts-ci-cd-lambda

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 01-node-ts-ci-cd-lambda/package-lock.json

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Zip
        run: npm run zip

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name basic-ci-cd \
            --zip-file fileb://function.zip
